services:
  - type: web
    name: ase-n8n
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "ase1234"
      - key: N8N_HOST
        value: ase-n8n.onrender.com
      - key: N8N_PORT
        value: 5678
